language: java

sudo: false

jdk:
  - oraclejdk8

services:
  - mysql

notifications:
  email:
    recipients:
      - antoniojk7@gmail.com
      - leomeister22@gmail.com
      - lucas.advc@gmail.com
      - skingk.f@gmail.com
      - do.guilherme@hotmail.com
      - iamferreirajp@gmail.com
      - adailson2@gmail.com


